title: Personal Recommendation Definition
description: Defines the criteria that constitute a personal recommendation in investment
  contexts
criteria:
- id: criterion_1
  name: Recipient Capacity
  description: is made to a person in their capacity as
  sub_criteria:
  - id: criterion_1a
    name: Investor Status
    description: an investor or potential investor
    sub_criteria: []
    sub_logic: null
  - id: criterion_1b
    name: Agent Status
    description: agent for an investor or a potential investor
    sub_criteria: []
    sub_logic: null
  sub_logic: any
- id: criterion_2
  name: Investment Action
  description: is for the person in (1) to do any of the following (whether as principal
    or agent)
  sub_criteria:
  - id: criterion_2a
    name: Trading Activities
    description: buy, sell, subscribe for, exchange, redeem, hold or underwrite a
      particular investment which is a security, a structured deposit or a relevant
      investment
    sub_criteria: []
    sub_logic: null
  - id: criterion_2b
    name: Rights Exercise
    description: exercise or not exercise any right conferred by such an investment
      to buy, sell, subscribe for, exchange or redeem such an investment
    sub_criteria: []
    sub_logic: null
  sub_logic: any
- id: criterion_3
  name: Personalization
  description: is
  sub_criteria:
  - id: criterion_3a
    name: Suitability Presentation
    description: presented as suitable for the person to whom it is made
    sub_criteria: []
    sub_logic: null
  - id: criterion_3b
    name: Circumstance Consideration
    description: based on a consideration of the circumstances of that person
    sub_criteria: []
    sub_logic: null
  sub_logic: any
- id: criterion_4
  name: Distribution Scope
  description: is not issued exclusively to the public
  sub_criteria: []
  sub_logic: null
logic: all
raw_text: 'A personal recommendation means a recommendation that:


  (1) is made to a person in their capacity as:

  (a) an investor or potential investor; or

  (b) agent for an investor or a potential investor;

  (2) is for the person in (1) to do any of the following (whether as principal or
  agent):

  (a) buy, sell, subscribe for, exchange, redeem, hold or underwrite a particular
  investment which is a security, a structured deposit or a relevant investment; or

  (b) exercise or not exercise any right conferred by such an investment to buy, sell,
  subscribe for, exchange or redeem such an investment;

  (3) is:

  (a) presented as suitable for the person to whom it is made; or

  (b) based on a consideration of the circumstances of that person; and

  (4) is not issued exclusively to the public.'
